# Generated by Django 3.2.5 on 2022-05-17 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendarStartDay', models.DateField()),
                ('calendarEndDay', models.DateField()),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examType', models.CharField(max_length=100)),
                ('examStartDay', models.DateField()),
                ('examEndDay', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Library_popularityList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Library_takeout_deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('limit_num', models.CharField(max_length=100)),
                ('deadline', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LinkUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intentName', models.CharField(max_length=100)),
                ('url_name', models.CharField(max_length=100)),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_place', models.CharField(max_length=30)),
                ('menu_time', models.CharField(max_length=30)),
                ('menu_day', models.CharField(max_length=30)),
                ('data1', models.TextField()),
                ('data2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('weather_date', models.DateField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('iconImage', models.CharField(max_length=30)),
                ('tempMax', models.FloatField()),
                ('tempMin', models.FloatField()),
                ('pop', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Convenience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=100)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deubot_app.place')),
            ],
        ),
    ]
